apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp1
  template:
    metadata:
      labels:
        app: nodeapp1
    spec:
      containers:
        - name: appa
          image: n01479079/nginx-webserver:latest
          command: ["/bin/sh"]
          args: ["-c", "echo 'Hello world'; exit 1"] # Add a command that exits with an error
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service-1
spec:
  selector:
    app: nodeapp1
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31110
